<?php

namespace ContainerXum3vOY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessDeniedHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\AccessDeniedHandler' shared autowired service.
     *
     * @return \App\Security\AccessDeniedHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authorization/AccessDeniedHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/AccessDeniedHandler.php';

        return $container->privates['App\\Security\\AccessDeniedHandler'] = new \App\Security\AccessDeniedHandler();
    }
}
