<?php

namespace ContainerXum3vOY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateApiKeyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateApiKey' shared autowired service.
     *
     * @return \App\Command\CreateApiKey
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateApiKey.php';

        $container->privates['App\\Command\\CreateApiKey'] = $instance = new \App\Command\CreateApiKey(($container->privates['App\\Repository\\PharmappConfigurationRepository'] ?? $container->load('getPharmappConfigurationRepositoryService')), ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setName('app:create-api-key');
        $instance->setAliases([0 => 'app:add-api-key']);
        $instance->setDescription('Créer une nouvelle clé api.');

        return $instance;
    }
}
