<?php

namespace Container2wAfSxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MedicationRepository' shared autowired service.
     *
     * @return \App\Repository\MedicationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MedicationRepository'] = new \App\Repository\MedicationRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
