version: "3.8"
services:

  database:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./config.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: pharmapp
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8082:80"
    restart: always
    networks:
      - dev

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: symfony
    ports:
      - "8080:80"
#    env_file:
#      - ../.env
    environment:
      DATABASE_URL: mysql://root:root@database:3306/pharmapp
      XDEBUG_CONFIG: remote_host=host.docker.internal
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - ../:/var/www
      - ./vhost:/etc/apache2/sites-enabled
    restart: always
#    links:
#      - database
    networks:
      - dev

#  webserver:
#    image: phpstorm/php-71-apache-xdebug-26
#    ports:
#      - "8080:80"
#    volumes:
#      - ../:/var/www/html
#    environment:
#      XDEBUG_CONFIG: remote_host=host.docker.internal

networks:
  dev:

volumes:
  db-data: