<?php

namespace Container3O0PUVU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateApiKeyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateApiKey' shared autowired service.
     *
     * @return \App\Command\CreateApiKey
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CreateApiKey.php';

        $container->privates['App\\Command\\CreateApiKey'] = $instance = new \App\Command\CreateApiKey(($container->privates['App\\Repository\\PharmappConfigurationRepository'] ?? $container->load('getPharmappConfigurationRepositoryService')), ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setName('app:create-api-key');
        $instance->setAliases([0 => 'app:add-api-key']);
        $instance->setDescription('Créer une nouvelle clé api.');

        return $instance;
    }
}
