<?php

namespace ContainerCuv1qTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BUMsMA2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.bUMsMA2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bUMsMA2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LoginController::register' => ['privates', '.service_locator.VVan16a', 'get_ServiceLocator_VVan16aService', true],
            'App\\Controller\\MedicationController::medicationAddDemand' => ['privates', '.service_locator.il4hCKp', 'get_ServiceLocator_Il4hCKpService', true],
            'App\\Controller\\MedicationController::medicationDetail' => ['privates', '.service_locator.il4hCKp', 'get_ServiceLocator_Il4hCKpService', true],
            'App\\Controller\\MedicationController::userMedicationAdd' => ['privates', '.service_locator.yUaseuv', 'get_ServiceLocator_YUaseuvService', true],
            'App\\Controller\\MedicationController::userMedicationAll' => ['privates', '.service_locator.jMNGSFm', 'get_ServiceLocator_JMNGSFmService', true],
            'App\\Controller\\MedicationController::userRequestMedication' => ['privates', '.service_locator.il4hCKp', 'get_ServiceLocator_Il4hCKpService', true],
            'App\\Controller\\UserController::reset' => ['privates', '.service_locator.LI1wy7E', 'get_ServiceLocator_LI1wy7EService', true],
            'App\\Controller\\UserController::sendEmail' => ['privates', '.service_locator.D4nGOut', 'get_ServiceLocator_D4nGOutService', true],
            'App\\Controller\\UserController::userUpdate' => ['privates', '.service_locator.o9gzd_n', 'get_ServiceLocator_O9gzdNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\LoginController:register' => ['privates', '.service_locator.VVan16a', 'get_ServiceLocator_VVan16aService', true],
            'App\\Controller\\MedicationController:medicationAddDemand' => ['privates', '.service_locator.il4hCKp', 'get_ServiceLocator_Il4hCKpService', true],
            'App\\Controller\\MedicationController:medicationDetail' => ['privates', '.service_locator.il4hCKp', 'get_ServiceLocator_Il4hCKpService', true],
            'App\\Controller\\MedicationController:userMedicationAdd' => ['privates', '.service_locator.yUaseuv', 'get_ServiceLocator_YUaseuvService', true],
            'App\\Controller\\MedicationController:userMedicationAll' => ['privates', '.service_locator.jMNGSFm', 'get_ServiceLocator_JMNGSFmService', true],
            'App\\Controller\\MedicationController:userRequestMedication' => ['privates', '.service_locator.il4hCKp', 'get_ServiceLocator_Il4hCKpService', true],
            'App\\Controller\\UserController:reset' => ['privates', '.service_locator.LI1wy7E', 'get_ServiceLocator_LI1wy7EService', true],
            'App\\Controller\\UserController:sendEmail' => ['privates', '.service_locator.D4nGOut', 'get_ServiceLocator_D4nGOutService', true],
            'App\\Controller\\UserController:userUpdate' => ['privates', '.service_locator.o9gzd_n', 'get_ServiceLocator_O9gzdNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\LoginController::register' => '?',
            'App\\Controller\\MedicationController::medicationAddDemand' => '?',
            'App\\Controller\\MedicationController::medicationDetail' => '?',
            'App\\Controller\\MedicationController::userMedicationAdd' => '?',
            'App\\Controller\\MedicationController::userMedicationAll' => '?',
            'App\\Controller\\MedicationController::userRequestMedication' => '?',
            'App\\Controller\\UserController::reset' => '?',
            'App\\Controller\\UserController::sendEmail' => '?',
            'App\\Controller\\UserController::userUpdate' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\LoginController:register' => '?',
            'App\\Controller\\MedicationController:medicationAddDemand' => '?',
            'App\\Controller\\MedicationController:medicationDetail' => '?',
            'App\\Controller\\MedicationController:userMedicationAdd' => '?',
            'App\\Controller\\MedicationController:userMedicationAll' => '?',
            'App\\Controller\\MedicationController:userRequestMedication' => '?',
            'App\\Controller\\UserController:reset' => '?',
            'App\\Controller\\UserController:sendEmail' => '?',
            'App\\Controller\\UserController:userUpdate' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
