<?php

namespace ContainerCuv1qTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YUaseuvService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.yUaseuv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yUaseuv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'medicationRepository' => ['privates', 'App\\Repository\\MedicationRepository', 'getMedicationRepositoryService', true],
            'medicationUserRepository' => ['privates', 'App\\Repository\\MedicationUserRepository', 'getMedicationUserRepositoryService', true],
        ], [
            'managerRegistry' => '?',
            'medicationRepository' => 'App\\Repository\\MedicationRepository',
            'medicationUserRepository' => 'App\\Repository\\MedicationUserRepository',
        ]);
    }
}
