<?php

namespace ContainerCuv1qTf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Il4hCKpService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.il4hCKp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.il4hCKp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medicationRepository' => ['privates', 'App\\Repository\\MedicationRepository', 'getMedicationRepositoryService', true],
        ], [
            'medicationRepository' => 'App\\Repository\\MedicationRepository',
        ]);
    }
}
