<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3O0PUVU\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3O0PUVU/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container3O0PUVU.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container3O0PUVU\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container3O0PUVU\App_KernelTestDebugContainer([
    'container.build_hash' => '3O0PUVU',
    'container.build_id' => '47503c5a',
    'container.build_time' => 1670425775,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3O0PUVU');
