<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEeLoYtL\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEeLoYtL/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerEeLoYtL.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerEeLoYtL\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerEeLoYtL\App_KernelTestDebugContainer([
    'container.build_hash' => 'EeLoYtL',
    'container.build_id' => 'b62b9fb2',
    'container.build_time' => 1670423277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEeLoYtL');
