<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDtTdx1G\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDtTdx1G/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDtTdx1G.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDtTdx1G\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDtTdx1G\App_KernelTestDebugContainer([
    'container.build_hash' => 'DtTdx1G',
    'container.build_id' => '90c0c779',
    'container.build_time' => 1670839415,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDtTdx1G');
