<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/auth/login']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\LoginController::register'], [], [['text', '/register']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/auth/logout']], [], [], []],
    'add_medication' => [[], ['_controller' => 'App\\Controller\\MedicationController::userMedicationAdd'], [], [['text', '/auth/medication/user/add']], [], [], []],
    'app_medication_usermedicationall' => [[], ['_controller' => 'App\\Controller\\MedicationController::userMedicationAll'], [], [['text', '/auth/medication/user/all']], [], [], []],
    'app_medication_userrequestmedication' => [[], ['_controller' => 'App\\Controller\\MedicationController::userRequestMedication'], [], [['text', '/auth/medication/request/all']], [], [], []],
    'app_medication_medicationdetail' => [[], ['_controller' => 'App\\Controller\\MedicationController::medicationDetail'], [], [['text', '/medication/detail']], [], [], []],
    'app_medication_medicationadddemand' => [[], ['_controller' => 'App\\Controller\\MedicationController::medicationAddDemand'], [], [['text', '/auth/medication/add-on-demand']], [], [], []],
    'app_user_userdetail' => [[], ['_controller' => 'App\\Controller\\UserController::userDetail'], [], [['text', '/auth/user/detail']], [], [], []],
    'app_user_userupdate' => [[], ['_controller' => 'App\\Controller\\UserController::userUpdate'], [], [['text', '/auth/user/update']], [], [], []],
    'app_user_sendemail' => [[], ['_controller' => 'App\\Controller\\UserController::sendEmail'], [], [['text', '/reset-password']], [], [], []],
    'app_user_reset' => [['token'], ['token' => null, '_controller' => 'App\\Controller\\UserController::reset'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/reset-password/reset']], [], [], []],
];
