<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Medication extends \App\Entity\Medication implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'cip', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'medicationUsers', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'typeMedications', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'isRequest', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'obsolete'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'cip', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'medicationUsers', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'typeMedications', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'isRequest', '' . "\0" . 'App\\Entity\\Medication' . "\0" . 'obsolete'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Medication $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCip(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCip', []);

        return parent::getCip();
    }

    /**
     * {@inheritDoc}
     */
    public function setCip(?string $cip): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCip', [$cip]);

        return parent::setCip($cip);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicationUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicationUsers', []);

        return parent::getMedicationUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedicationUser(\App\Entity\MedicationUser $medicationUser): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedicationUser', [$medicationUser]);

        return parent::addMedicationUser($medicationUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedicationUser(\App\Entity\MedicationUser $medicationUser): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedicationUser', [$medicationUser]);

        return parent::removeMedicationUser($medicationUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeMedications(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeMedications', []);

        return parent::getTypeMedications();
    }

    /**
     * {@inheritDoc}
     */
    public function addTypeMedication(\App\Entity\TypeMedication $typeMedication): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTypeMedication', [$typeMedication]);

        return parent::addTypeMedication($typeMedication);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTypeMedication(\App\Entity\TypeMedication $typeMedication): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTypeMedication', [$typeMedication]);

        return parent::removeTypeMedication($typeMedication);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRequest(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRequest', []);

        return parent::getIsRequest();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRequest(?bool $isRequest): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRequest', [$isRequest]);

        return parent::setIsRequest($isRequest);
    }

    /**
     * {@inheritDoc}
     */
    public function getObsolete(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObsolete', []);

        return parent::getObsolete();
    }

    /**
     * {@inheritDoc}
     */
    public function setObsolete(?bool $obsolete): \App\Entity\Medication
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObsolete', [$obsolete]);

        return parent::setObsolete($obsolete);
    }

}
